version: '3.7'

services:

  mongodb_migrate:
    image: mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbUser
      MONGO_INITDB_ROOT_PASSWORD: somePass
      MONGO_INITDB_DATABASE: todoDB
    ports:
      - '27017:27017'

  mongodb_migrate_seed:
    build: ./mongodb_migrate_seed
    depends_on:
      - mongodb_migrate

  mongo:
    build: ./mongodb_replica
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbUser
      MONGO_INITDB_ROOT_PASSWORD: somePass
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27018
    ports:
      - '27018:27018'